apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: le3arn2code-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: quay.io/openshift/origin-nginx:latest
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace: le3arn2code-dev
spec:
  selector:
    app: test-app
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
