apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: secrets-lab
type: Opaque
data:
  api-key: YWJjZGVmZ2hpams=
  jwt-secret: bXlzdXBlcnNlY3JldGp3dA==
  encryption-key: ZW5jcnlwdGlvbmtleTEyMw==