apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app-deployment
  namespace: secrets-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
      - name: app-container
        image: nginx:latest
        envFrom:
        - secretRef:
            name: app-secret
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PASSWORD