apiVersion: v1
kind: Pod
metadata:
  name: secret-consumer-pod
  namespace: secrets-lab
spec:
  containers:
  - name: app-container
    image: nginx:latest
    env:
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_USERNAME
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_PASSWORD
    - name: DATABASE_HOST
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: DB_HOST
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: api-key