apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  namespace: secrets-lab
spec:
  containers:
  - name: app-container
    image: nginx:latest
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Checking secrets...'; ls -la /etc/secrets/; sleep 30; done"]
  volumes:
  - name: secret-volume
    secret:
      secretName: database-secret