apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-user
  namespace: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user
  namespace: testing