apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: le3arn2code-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: insecure-container
        image: nginx:1.20
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 80
