apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-viewer-binding
  namespace: le3arn2code-dev
subjects:
- kind: User
  name: le3arn2code
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-viewer-role
  apiGroup: rbac.authorization.k8s.io
