apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
      default: main
    - name: image-name
    - name: app-name
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      taskRef:
        name: buildah-build-push
      runAfter: [fetch-source]
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy-application
      taskRef:
        name: deploy-app
      runAfter: [build-image]
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: APP_NAME
          value: $(params.app-name)
