apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  params:
    - name: IMAGE
      type: string
    - name: APP_NAME
      type: string
  steps:
    - name: deploy
      image: registry.redhat.io/openshift4/ose-cli:latest
      script: |
        #!/bin/bash
        set -e
        if ! oc get deployment $(params.APP_NAME) >/dev/null 2>&1; then
          oc create deployment $(params.APP_NAME) --image=$(params.IMAGE)
        else
          oc set image deployment/$(params.APP_NAME) $(params.APP_NAME)=$(params.IMAGE)
        fi
        if ! oc get service $(params.APP_NAME) >/dev/null 2>&1; then
          oc expose deployment $(params.APP_NAME) --port=8080
        fi
        if ! oc get route $(params.APP_NAME) >/dev/null 2>&1; then
          oc expose service $(params.APP_NAME)
        fi
        oc rollout status deployment/$(params.APP_NAME) --timeout=300s
