apiVersion: v1
kind: Pod
metadata:
  name: storage-issue-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: non-existent-pvc
